api_platform:
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    defaults:
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
    mapping:
        paths:
            - '%kernel.project_dir%/config/api-platform'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: true
            items_per_page_parameter_name: limit
