sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        ignore_exceptions:
            - 'Symfony\Component\ErrorHandler\Error\FatalError'
            - 'Symfony\Component\Debug\Exception\FatalErrorException'
            - 'ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException'
            - 'App\Exception\NoSuchUserException'
            - 'App\Exception\NoVerifiedEmailException'
            - 'App\Exception\TokenRefreshRequiredException'
            - 'Auth0\SDK\Exception\InvalidTokenException'
            - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
            - 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException'
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
            - 'Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException'
            - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
            - 'Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException'
            - 'Symfony\Component\Serializer\Exception\NotEncodableValueException'
